// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: proto/service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FaultTolerant_Execute_FullMethodName = "/FaultTolerant/Execute"
	FaultTolerant_Stream_FullMethodName  = "/FaultTolerant/Stream"
	FaultTolerant_Promote_FullMethodName = "/FaultTolerant/Promote"
)

// FaultTolerantClient is the client API for FaultTolerant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaultTolerantClient interface {
	Execute(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	Stream(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error)
	Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error)
}

type faultTolerantClient struct {
	cc grpc.ClientConnInterface
}

func NewFaultTolerantClient(cc grpc.ClientConnInterface) FaultTolerantClient {
	return &faultTolerantClient{cc}
}

func (c *faultTolerantClient) Execute(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, FaultTolerant_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *faultTolerantClient) Stream(ctx context.Context, in *Request, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FaultTolerant_ServiceDesc.Streams[0], FaultTolerant_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FaultTolerant_StreamClient = grpc.ServerStreamingClient[Response]

func (c *faultTolerantClient) Promote(ctx context.Context, in *PromoteRequest, opts ...grpc.CallOption) (*PromoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteResponse)
	err := c.cc.Invoke(ctx, FaultTolerant_Promote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaultTolerantServer is the server API for FaultTolerant service.
// All implementations must embed UnimplementedFaultTolerantServer
// for forward compatibility.
type FaultTolerantServer interface {
	Execute(context.Context, *Request) (*Response, error)
	Stream(*Request, grpc.ServerStreamingServer[Response]) error
	Promote(context.Context, *PromoteRequest) (*PromoteResponse, error)
	mustEmbedUnimplementedFaultTolerantServer()
}

// UnimplementedFaultTolerantServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFaultTolerantServer struct{}

func (UnimplementedFaultTolerantServer) Execute(context.Context, *Request) (*Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedFaultTolerantServer) Stream(*Request, grpc.ServerStreamingServer[Response]) error {
	return status.Error(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedFaultTolerantServer) Promote(context.Context, *PromoteRequest) (*PromoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Promote not implemented")
}
func (UnimplementedFaultTolerantServer) mustEmbedUnimplementedFaultTolerantServer() {}
func (UnimplementedFaultTolerantServer) testEmbeddedByValue()                       {}

// UnsafeFaultTolerantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaultTolerantServer will
// result in compilation errors.
type UnsafeFaultTolerantServer interface {
	mustEmbedUnimplementedFaultTolerantServer()
}

func RegisterFaultTolerantServer(s grpc.ServiceRegistrar, srv FaultTolerantServer) {
	// If the following call panics, it indicates UnimplementedFaultTolerantServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FaultTolerant_ServiceDesc, srv)
}

func _FaultTolerant_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaultTolerantServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaultTolerant_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaultTolerantServer).Execute(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _FaultTolerant_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FaultTolerantServer).Stream(m, &grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FaultTolerant_StreamServer = grpc.ServerStreamingServer[Response]

func _FaultTolerant_Promote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaultTolerantServer).Promote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaultTolerant_Promote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaultTolerantServer).Promote(ctx, req.(*PromoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FaultTolerant_ServiceDesc is the grpc.ServiceDesc for FaultTolerant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaultTolerant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FaultTolerant",
	HandlerType: (*FaultTolerantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _FaultTolerant_Execute_Handler,
		},
		{
			MethodName: "Promote",
			Handler:    _FaultTolerant_Promote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _FaultTolerant_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/service.proto",
}
